-- Generated by Mocodo 4.3.2

CREATE TABLE AEROPORT (
  PRIMARY KEY (nom_aeroport),
  nom_aeroport VARCHAR(100) NOT NULL,
  id_ville   INT(100) NOT NULL
);

CREATE TABLE PAYS (
  PRIMARY KEY (id_pays),
  id_pays  INT(100) NOT NULL,
  nom_pays VARCHAR(5)
);

CREATE TABLE TERMINAL (
  PRIMARY KEY (nom_aeroport, nom_terminal),
  nom_aeroport VARCHAR(100) NOT NULL,
  nom_terminal VARCHAR(100) NOT NULL
);

CREATE TABLE VILLE (
  PRIMARY KEY (id_ville),
  id_ville INT(100) NOT NULL,
  nom_ville  VARCHAR(100),
  id_pays    INT(100) NOT NULL
);

CREATE TABLE VOL (
  PRIMARY KEY (nom_compagnie, num_vol, date_heure_depart),
  nom_compagnie             VARCHAR(100) NOT NULL,
  num_vol                   VARCHAR(40) NOT NULL,
  date_heure_depart         DATETIME(42) NOT NULL,
  date_heure_arrivee_prevue DATETIME(42),
  nom_aeroport_1            VARCHAR(100) NOT NULL,
  nom_terminal_1            VARCHAR(100) NOT NULL,
  nom_aeroport_2            VARCHAR(100) NOT NULL,
  nom_terminal_2            VARCHAR(100) NOT NULL
);

ALTER TABLE AEROPORT ADD FOREIGN KEY (id_ville) REFERENCES VILLE (id_ville);

ALTER TABLE TERMINAL ADD FOREIGN KEY (nom_aeroport) REFERENCES AEROPORT (nom_aeroport);

ALTER TABLE VILLE ADD FOREIGN KEY (id_pays) REFERENCES PAYS (id_pays);

ALTER TABLE VOL ADD FOREIGN KEY (nom_aeroport_2, nom_terminal_2) REFERENCES TERMINAL (nom_aeroport, nom_terminal);
ALTER TABLE VOL ADD FOREIGN KEY (nom_aeroport_1, nom_terminal_1) REFERENCES TERMINAL (nom_aeroport, nom_terminal);
